### ISSUE TITLE
NPC: Rampaging Furbolg not attackable

### ISSUE THREAD

**Issue by Sundorian** [Hazor-Hellscream/Project-Hellscream-Info#1057]
Ok so this time I am doing this as best as I can.  

NPC - Rampaging Furbolg in Ashenvale   id 34620 - (from wowhead)

Npc shows to be hostile but and red but is unattackable

![image](https://user-images.githubusercontent.com/45952468/81774671-c34d4f00-94b0-11ea-8323-5b055ba360d9.png)

**Comment by EyalMK** [comment]
Fixed. Going to script the fight with Silverwind Defenders soon enough.

**Comment by Sundorian** [comment]
still not attackable, but if its a scriped deal and players arent able to interfere then who know i guess

Ok so I stood there awhile and several spawned and attacked the silverwind defenders, and while they were they were attackable but if the silverwind defender died the turned to be unattackable.  It wasnt all of them just a few.

**Comment by EyalMK** [comment]
The fix just wasn't pushed live. Tested and fixed. Scripting the fight as we speak. Closed.
