### ISSUE TITLE
Quest-[Disrupt their reinforcements: 10208]

### ISSUE THREAD

**Issue by Goretech** [Hazor-Hellscream/Project-Hellscream-Info#815]
Quest item only works for 1 portal.

**Comment by EyalMK** [comment]
Fixed. Please Test.

**Comment by Goretech** [comment]
Still dont work
![WoWScrnShot_042120_013110](https://user-images.githubusercontent.com/60852022/79805891-d49eb200-836f-11ea-9380-5011a1932b49.jpg)

**Comment by EyalMK** [comment]
You're missing https://www.wowhead.com/item=28106/kingstons-primers
You need to build it from 4 Demonic Rune Stones and they're consumable.
