### ISSUE TITLE
Quest - [The Fargodeep Mine: 62]

### ISSUE THREAD

**Issue by ShaldarWoW** [Hazor-Hellscream/Project-Hellscream-Info#95]
Quest - [The Fargodeep Mine: 62]

The quest progression requirement is sometimes inconsistent and the quest can't be completed reliably.

Probably related to #6 

WoW Head link:
(https://www.wowhead.com/quest=62/the-fargodeep-mine)

**Comment by ShaldarWoW** [comment]
After recent updates it can be completed reliably. There's still a bug where the quest log doesn't reflect the progress.

![imagen](https://user-images.githubusercontent.com/60824117/74605827-d75cfc80-50cb-11ea-9eb9-285847a93870.png)

**Comment by ShaldarWoW** [comment]
Fixed in the last update.

**Comment by Rorhn** [comment]
Seems to be an issue again as of today, tried walking in and out of multiple entrances and all throughout the mine. Couldn't get it to complete.

**Comment by Rorhn** [comment]
Still an issue as of today, you should be able to walk in and after about 10 seconds the quest should complete.
https://youtu.be/gIktDPJAuiA?t=63
